# columuns and data for each table

CUSTOMER_COLUMNS = {
    "ID", "FIRST_NAME", "LAST_NAME", "ADDRESS", "CITY", "STATE",
    "ZIP_CODE", "PHONE_NUMBER", "SSN", "USERNAME", "PASSWORD"
}

ACCOUNT_COLUMNS = {
    "ID", "CUSTOMER_ID", "TYPE", "BALANCE"
}

TRANSACTION_COLUMNS = {
    "ID", "ACCOUNT_ID", "DATE", "AMOUNT", "DESCRIPTION"
}

STOCK_COLUMNS = {
    "ID", "SYMBOL", "DATE", "CLOSING_PRICE"
}

COMPANY_COLUMNS = {
    "SYMBOL", "NAME"
}

POSITIONS_COLUMNS = {
    "POSITION_ID", "CUSTOMER_ID", "NAME", "SYMBOL", "SHARES", "PURCHASE_PRICE"
}
